In [2]:
from google.colab import files
uploaded = files.upload()

Saving sample_100.csv to sample_100.csv

In [5]:
import pandas as pd
import io

# Get the uploaded file name
file_name = list(uploaded.keys())[0]

# Read pipe-delimited file into pandas DataFrame
df = pd.read_csv(io.BytesIO(uploaded[file_name]), sep='|')

In [6]:
df.columns

Index(['id', 'tid', 'bates', 'type', 'description', 'title', 'author',
       'mentioned', 'attending', 'copied', 'recipient', 'redacted',
       'collection_name', 'pages', 'exhibit_number', 'document_date',
       'date_added_ucsf', 'date_modified_ucsf', 'date_added_industry',
       'date_modified_industry', 'date_produced', 'date_shipped',
       'deposition_date', 'date_privilege_logged', 'case', 'industry', 'drug',
       'adverse_ruling', 'area', 'bates_alternate', 'box', 'brand', 'country',
       'language', 'court', 'format', 'express_waiver', 'file', 'genre',
       'keywords', 'bates_master', 'other_number', 'request_number',
       'minnesota_request_number', 'privilege_code', 'topic', 'witness',
       'cited', 'availability', 'grant_number', 'source', 'folder', 'series',
       'chemical', 'food', 'rights', 'ocr_text'],
      dtype='object')

In [7]:
# Display first few rows
df

,id,tid,bates,type,description,title,author,mentioned,attending,copied,...,cited,availability,grant_number,source,folder,series,chemical,food,rights,ocr_text
0,gqfj0045,ekq76b00,6610,,,Re: Package Design Attractive to Kids,"Gaberman, Philip Creative Dir, Robert, Brian A...",Lorillard Inc.,,,...,,"public, no restrictions",,,,,,,,v-> ^x^^a^^^i^^^/C^^^SS^^^�^&^ tPf^SOQ/...
1,yqfj0045,mkq76b00,91257509-91257510,,,Get Box BDI and Menthol BDI,,Lorillard Inc.,,,...,,"public, no restrictions",,,,,,,,"<ocr>i G~iC.Lo~- . ~w X- t'J "" """""" aPs~-4L-a~ ..."
2,zrfj0045,ilq76b00,03351530,,,Re: Cigarette Advertising in Books,"Puccio, Lucy",Lorillard Inc.,,,...,,"public, no restrictions",,,,,,,,<ocr>Mrs. Marguerite L. Saeckerr.'Librarian Oa...
3,lsfj0045,plq76b00,85395147-8539155,,,Subject: Old Gold Parent Focus Groups,"Sellers, Richard B",Lorillard Inc.,,"Vila, B, Andes, J, Black, N, Gold, J, Hoefer, ...",...,,"public, no restrictions",,,,,,,,85395147 Page 1 of 14 y/7 Jaa* _� ...
4,ttfj0045,nmq76b00,85297330,,,Re: Newport Cigarette Ad Models,"Minghenelli, Sharon",Lorillard Inc.,,,...,,"public, no restrictions",,,,,,,,<ocr>I would like some assurance that your Pub...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
94,hmlj0045,yos76b00,201069714Exhibit1781,,,"Re: R&D Cost Sharing, Confidentiality and Lice...","Kohnhorst, Earl Exec VP",Brown and Williamson Tobacco Corp.,,,...,,"public, no restrictions",,,,,,,,3&o> BROIWAUUIIUISON TOBACCO CQRJOILW.QS ...
95,pllj0045,qos76b00,301122439-301122440Exhibit11,,,Re: Cost and Risk Pooling Agreement,"*Cummins, B. D. (use Cummins, Bob D.)",Brown and Williamson Tobacco Corp.,,,...,,"public, no restrictions",,,,,,,,/ A ...
96,nnlj0045,ups76b00,LgToNON19970611.Lp,,,"Arch, et al. Plainiffs, v. The American Tobacc...","Blancato, William A Esq",Non-Tobacco Company,,,...,,"public, no restrictions",,,,,,,,3&S oS/13/97 FRI 12:18 FAX 215 ...
97,nylj0045,kqs76b00,5206627915-506628018,,,Cigarette Liability Litigation--Background and...,"James, A Fyock and Associates",R.J. Reynolds Tobacco Co.,,,...,,"public, no restrictions",,,,,,,,PRIVILEGED & CONFIDENTIAL Privileged end wo...
98,rqlj0045,urs76b00,01417830-01417840Exhibit101,,,RL Enrichment Project,,Lorillard Inc.,,,...,,"public, no restrictions",,,,,,,,RL Enrichment Project INTRODUCTION This ...

In [8]:
df.iloc[0]['ocr_text']

'v->        ^x^^a^^^i^^^/C^^^SS^^^�^&^ tPf^SOQ/S - �&myteog-g6t    August 13th,   i.970    Frofessor Charles Seide    Cooper  Union    Cooper  Square    New York,   New York    Dear  Professor  Seide:    We\'re adults.     You\'ve got a group of talented kids.     Hence this letter. .    We have been asked by. our client to come up �with a package design.... a design that is attractive to kids.... (young adults) .    We were wondering if this project might serve as a challenging assignment for your package design class(es) 4    The assignment is as follows:    To design a \' cigarette package and cigarette carton that has selling appeal ..to the "youth market".     The new product nam s is  "Kicks",   (a new cigarette)    Guidelines, that must be followed include:    A." The actual package  contains ten cigarettes.... not the usual twenty*.    B.   The words:   "delux length!1 must appear on the package.    C.   The words:   "a product of L-orillard Greensboro, N.C.,  U.S.A.".must also appear.    D.   The words:   "Caution:   Cigarette Smoking MaV\\ Be Hazardous To Your Health" must be included/. \\ on the package.                                               [\\     ,/\\^F    A SALES PROMOTION AGENCY    07/24  \'95 10:20     pgNbr=1 %tim <8K*^@�^e^^�^tfto    Cont.   Professor Seide    E.  The "seal closure" on the package top must say \'             "a product of LiOrUlard,   10 cigarettes Class  (A)."    Note:          While this cigarette is geared to the youth market,    no attempt (obvious)   can be made to encourage persons under \'twenty-on� to smoke.    The package design should be geared to attract the youthful eye.... not the ever-watchful eye of the Federal Government.    If one of your, students presents a package-carton design (s) that is accepted (design chosen for new package-carton)   either that person will be awarded an agreed upon sum of money, or �your school will be given an agreed sum of tnoney for scholarships-   � T^iese methods of paymant,  along with any others that you might suggest,  "can be discussed at a later date.    I don\'t know if you can entertain such an idea for a class\' project,  but I would appreciate hearing from you regarding same.    Smc�r,e}y,.    IS         -    -    ^r    Hiilip Gaberman Creative Director    fc\'\\    A SALES PROMOTION AGENCY    07/24 \'95 10:20 pgNbr=2 '

In [9]:
!pip install pandasql

Collecting pandasql
  Downloading pandasql-0.7.3.tar.gz (26 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from pandasql) (2.0.2)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from pandasql) (2.2.2)
Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.12/dist-packages (from pandasql) (2.0.47)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->pandasql) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->pandasql) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->pandasql) (2025.3)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy->pandasql) (3.3.2)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy->pandasql) (4.15.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->pandasql) (1.17.0)
Building wheels for collected packages: pandasql
  Building wheel for pandasql (setup.py) ... done
  Created wheel for pandasql: filename=pandasql-0.7.3-py3-none-any.whl size=26773 sha256=5f95e9d8ffb4825fff4e61a1a0790d8b9b1d31ca424e1acdacebd72bf8ad510b
  Stored in directory: /root/.cache/pip/wheels/15/a1/e7/6f92f295b5272ae5c02365e6b8fa19cb93f16a537090a1cf27
Successfully built pandasql
Installing collected packages: pandasql
Successfully installed pandasql-0.7.3

In [10]:
from pandasql import sqldf

# Global query function
pysqldf = lambda q: sqldf(q, globals())

In [20]:
sql_non_tobacco = """
SELECT *
FROM df
WHERE mentioned = 'Non-Tobacco Company'
"""

In [21]:
pysqldf(sql_non_tobacco)

,id,tid,bates,type,description,title,author,mentioned,attending,copied,...,availability,grant_number,source,folder,series,chemical,food,rights,ocr_text,vader_compound_500
0,txgj0045,ppq76b00,AmYoNON19871207.Nr,,,Cigarette Advertising in the Metrodome Fact Sheet,"Association, for Nonsmokers, Howard, Don",Non-Tobacco Company,,,...,"public, no restrictions",,,,,,,,"Date: December T, 1987 ...",0.0000
1,tggj0045,joq76b00,AmYoNON00000000.Sm,,,Cigarette Seduction: How Cigarettes Brands Work,"Brody, Alan",Non-Tobacco Company,,,...,"public, no restrictions",,,,,,,,Michael Cummings PhD From: Gene Borio...,-0.3802
2,gxgj0045,cpq76b00,03025284-03025287,,,Brand Preference and Advertising Recall in Ado...,"Chapman, Simon, Fitzgerald, Bill",Non-Tobacco Company,,,...,"public, no restrictions",,,,,,,,"<ocr>M, Y � ~ PUBLIC HEALTH BRIEFS 7. Venters ...",0.2960
3,jjgj0045,vpq76b00,87650312,,,Cigarette Ads in Kids' Movies,"Tobacco, and Youth Reporter",Non-Tobacco Company,,,...,"public, no restrictions",,,,,,,,"<ocr>71 , 1BACCO AND YOUTh REPORTER2 Cigarette...",0.8986
4,pjgj0045,bqq76b00,87533875-87533881,,,"Remarks by Louis W. Sullivan, M.D. Secretary o...","Sullivan, Louis W MD",Non-Tobacco Company,,,...,"public, no restrictions",,,,,,,,"<ocr>FOR RELEASE UPON DELIVERY FRIDAY, FEBRUAR...",0.8384
5,xkgj0045,kqq76b00,87718858-87718861,,,Brand Logo Recognition by Children Aged 3 to 6...,"Fischer, Paul M., M.D., Goldstein, Adam O MD, ...",Non-Tobacco Company,,,...,"public, no restrictions",,,,,,,,<ocr>r Brand Logo Recognition by Children Aged...,0.0000
6,zkgj0045,wqq76b00,6794,,,"Kids See Many Cigaret Ads on TV, FTC Finds","Advertising, Age",Non-Tobacco Company,,,...,"public, no restrictions",,,,,,,,sing flge | AvrflM.I�4 tt CMfc � Oapr � ...,-0.4588
7,lrhj0045,rer76b00,2062510266,,,Re: ADMHA Reorganization Act,"DeLay, Tom Rep",Non-Tobacco Company,,,...,"public, no restrictions",,,,,,,,<ocr>C[1MM11Trt (1M 0k/'W/VMNIAtIONS tYw qYp.M...,0.6103
8,kmxj0045,llr76b00,50552,,,Texas Risk Factor Report: Behavioral Risk Fact...,"Texas, Department of Health",Non-Tobacco Company,,,...,"public, no restrictions",,,,,,,,-W7 �^|j i ...,-0.3400
9,krxj0045,por76b00,C1-94-8565,,,"Minnesota vs. Tobacco February 4, 1998","Blue, Cross and Blue Shield of Minnesota, Stat...",Non-Tobacco Company,,,...,"public, no restrictions",,,,,,,,"Minnesota vs. Tobacco February 4, 1998 http...",0.0000
10,zkkj0045,jes76b00,01585983-01585985,,,Evaluation of Staff Report on Consumer Respons...,"Bureau, of Economics Federal Trade Commission",Non-Tobacco Company,,,...,"public, no restrictions",,,,,,,,"<ocr>'--Evaluation of r~.., ..- _.. - v!' Staf...",-0.4184
11,gjlj0045,bns76b00,345-365,,,"United States of America, Plaintiff, v. R. J. ...","[Calahan, James A] United States District Judge",Non-Tobacco Company,,,...,"public, no restrictions",,,,,,,,3o? NATIONAL ARCHIVES AND RECORDS ADMINISTR...,0.6416
12,nnlj0045,ups76b00,LgToNON19970611.Lp,,,"Arch, et al. Plainiffs, v. The American Tobacc...","Blancato, William A Esq",Non-Tobacco Company,,,...,"public, no restrictions",,,,,,,,3&S oS/13/97 FRI 12:18 FAX 215 ...,0.5766

In [22]:
sql_tobacco = """
SELECT *
FROM df
WHERE mentioned <> 'Non-Tobacco Company'
"""

In [24]:
pysqldf(sql_tobacco)

,id,tid,bates,type,description,title,author,mentioned,attending,copied,...,availability,grant_number,source,folder,series,chemical,food,rights,ocr_text,vader_compound_500
0,gqfj0045,ekq76b00,6610,,,Re: Package Design Attractive to Kids,"Gaberman, Philip Creative Dir, Robert, Brian A...",Lorillard Inc.,,,...,"public, no restrictions",,,,,,,,v-> ^x^^a^^^i^^^/C^^^SS^^^�^&^ tPf^SOQ/...,0.8555
1,yqfj0045,mkq76b00,91257509-91257510,,,Get Box BDI and Menthol BDI,,Lorillard Inc.,,,...,"public, no restrictions",,,,,,,,"<ocr>i G~iC.Lo~- . ~w X- t'J "" """""" aPs~-4L-a~ ...",0.0000
2,zrfj0045,ilq76b00,03351530,,,Re: Cigarette Advertising in Books,"Puccio, Lucy",Lorillard Inc.,,,...,"public, no restrictions",,,,,,,,<ocr>Mrs. Marguerite L. Saeckerr.'Librarian Oa...,0.6249
3,lsfj0045,plq76b00,85395147-8539155,,,Subject: Old Gold Parent Focus Groups,"Sellers, Richard B",Lorillard Inc.,,"Vila, B, Andes, J, Black, N, Gold, J, Hoefer, ...",...,"public, no restrictions",,,,,,,,85395147 Page 1 of 14 y/7 Jaa* _� ...,0.0000
4,ttfj0045,nmq76b00,85297330,,,Re: Newport Cigarette Ad Models,"Minghenelli, Sharon",Lorillard Inc.,,,...,"public, no restrictions",,,,,,,,<ocr>I would like some assurance that your Pub...,0.7003
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
81,pjlj0045,kns76b00,LG2015199-LG2015206,,,Re: Laws and Litigation,,"Liggett Group, Inc. (Liggett and Meyers)",,,...,"public, no restrictions",,,,,,,,A <!--abcdefghijklmnopqrstuvwxyz_page_end--...,0.0000
82,hmlj0045,yos76b00,201069714Exhibit1781,,,"Re: R&D Cost Sharing, Confidentiality and Lice...","Kohnhorst, Earl Exec VP",Brown and Williamson Tobacco Corp.,,,...,"public, no restrictions",,,,,,,,3&o> BROIWAUUIIUISON TOBACCO CQRJOILW.QS ...,0.9493
83,pllj0045,qos76b00,301122439-301122440Exhibit11,,,Re: Cost and Risk Pooling Agreement,"*Cummins, B. D. (use Cummins, Bob D.)",Brown and Williamson Tobacco Corp.,,,...,"public, no restrictions",,,,,,,,/ A ...,0.7845
84,nylj0045,kqs76b00,5206627915-506628018,,,Cigarette Liability Litigation--Background and...,"James, A Fyock and Associates",R.J. Reynolds Tobacco Co.,,,...,"public, no restrictions",,,,,,,,PRIVILEGED & CONFIDENTIAL Privileged end wo...,0.5622
85,rqlj0045,urs76b00,01417830-01417840Exhibit101,,,RL Enrichment Project,,Lorillard Inc.,,,...,"public, no restrictions",,,,,,,,RL Enrichment Project INTRODUCTION This ...,0.4019

In [25]:
sql = """
SELECT *
FROM (
    SELECT *
    FROM df
    WHERE mentioned = 'Non-Tobacco Company'
)

UNION ALL

SELECT *
FROM (
    SELECT *
    FROM df
    WHERE mentioned != 'Non-Tobacco Company'
       OR mentioned IS NULL
)
"""

In [26]:
df_mentioned = pysqldf(sql)

In [27]:
df_mentioned

,id,tid,bates,type,description,title,author,mentioned,attending,copied,...,availability,grant_number,source,folder,series,chemical,food,rights,ocr_text,vader_compound_500
0,txgj0045,ppq76b00,AmYoNON19871207.Nr,,,Cigarette Advertising in the Metrodome Fact Sheet,"Association, for Nonsmokers, Howard, Don",Non-Tobacco Company,,,...,"public, no restrictions",,,,,,,,"Date: December T, 1987 ...",0.0000
1,tggj0045,joq76b00,AmYoNON00000000.Sm,,,Cigarette Seduction: How Cigarettes Brands Work,"Brody, Alan",Non-Tobacco Company,,,...,"public, no restrictions",,,,,,,,Michael Cummings PhD From: Gene Borio...,-0.3802
2,gxgj0045,cpq76b00,03025284-03025287,,,Brand Preference and Advertising Recall in Ado...,"Chapman, Simon, Fitzgerald, Bill",Non-Tobacco Company,,,...,"public, no restrictions",,,,,,,,"<ocr>M, Y � ~ PUBLIC HEALTH BRIEFS 7. Venters ...",0.2960
3,jjgj0045,vpq76b00,87650312,,,Cigarette Ads in Kids' Movies,"Tobacco, and Youth Reporter",Non-Tobacco Company,,,...,"public, no restrictions",,,,,,,,"<ocr>71 , 1BACCO AND YOUTh REPORTER2 Cigarette...",0.8986
4,pjgj0045,bqq76b00,87533875-87533881,,,"Remarks by Louis W. Sullivan, M.D. Secretary o...","Sullivan, Louis W MD",Non-Tobacco Company,,,...,"public, no restrictions",,,,,,,,"<ocr>FOR RELEASE UPON DELIVERY FRIDAY, FEBRUAR...",0.8384
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
94,pjlj0045,kns76b00,LG2015199-LG2015206,,,Re: Laws and Litigation,,"Liggett Group, Inc. (Liggett and Meyers)",,,...,"public, no restrictions",,,,,,,,A <!--abcdefghijklmnopqrstuvwxyz_page_end--...,0.0000
95,hmlj0045,yos76b00,201069714Exhibit1781,,,"Re: R&D Cost Sharing, Confidentiality and Lice...","Kohnhorst, Earl Exec VP",Brown and Williamson Tobacco Corp.,,,...,"public, no restrictions",,,,,,,,3&o> BROIWAUUIIUISON TOBACCO CQRJOILW.QS ...,0.9493
96,pllj0045,qos76b00,301122439-301122440Exhibit11,,,Re: Cost and Risk Pooling Agreement,"*Cummins, B. D. (use Cummins, Bob D.)",Brown and Williamson Tobacco Corp.,,,...,"public, no restrictions",,,,,,,,/ A ...,0.7845
97,nylj0045,kqs76b00,5206627915-506628018,,,Cigarette Liability Litigation--Background and...,"James, A Fyock and Associates",R.J. Reynolds Tobacco Co.,,,...,"public, no restrictions",,,,,,,,PRIVILEGED & CONFIDENTIAL Privileged end wo...,0.5622
98,rqlj0045,urs76b00,01417830-01417840Exhibit101,,,RL Enrichment Project,,Lorillard Inc.,,,...,"public, no restrictions",,,,,,,,RL Enrichment Project INTRODUCTION This ...,0.4019

In [28]:
# does the sentiment differ for non-tobacco produced or tobacco-produced?
# do they differ substantially in subject matter (health, entertainment, outdoors)?

In [29]:
!pip install vaderSentiment

Requirement already satisfied: vaderSentiment in /usr/local/lib/python3.12/dist-packages (3.3.2)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from vaderSentiment) (2.32.4)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->vaderSentiment) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->vaderSentiment) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->vaderSentiment) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->vaderSentiment) (2026.1.4)

In [30]:
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer
analyzer = SentimentIntensityAnalyzer()

In [31]:
def vader_first_500(text):
    if not isinstance(text, str) or not text.strip():
        return None
    short_text = text[:500]
    return analyzer.polarity_scores(short_text)['compound']

df['vader_compound_500'] = df['ocr_text'].apply(vader_first_500)

In [32]:
df

,id,tid,bates,type,description,title,author,mentioned,attending,copied,...,availability,grant_number,source,folder,series,chemical,food,rights,ocr_text,vader_compound_500
0,gqfj0045,ekq76b00,6610,,,Re: Package Design Attractive to Kids,"Gaberman, Philip Creative Dir, Robert, Brian A...",Lorillard Inc.,,,...,"public, no restrictions",,,,,,,,v-> ^x^^a^^^i^^^/C^^^SS^^^�^&^ tPf^SOQ/...,0.8555
1,yqfj0045,mkq76b00,91257509-91257510,,,Get Box BDI and Menthol BDI,,Lorillard Inc.,,,...,"public, no restrictions",,,,,,,,"<ocr>i G~iC.Lo~- . ~w X- t'J "" """""" aPs~-4L-a~ ...",0.0000
2,zrfj0045,ilq76b00,03351530,,,Re: Cigarette Advertising in Books,"Puccio, Lucy",Lorillard Inc.,,,...,"public, no restrictions",,,,,,,,<ocr>Mrs. Marguerite L. Saeckerr.'Librarian Oa...,0.6249
3,lsfj0045,plq76b00,85395147-8539155,,,Subject: Old Gold Parent Focus Groups,"Sellers, Richard B",Lorillard Inc.,,"Vila, B, Andes, J, Black, N, Gold, J, Hoefer, ...",...,"public, no restrictions",,,,,,,,85395147 Page 1 of 14 y/7 Jaa* _� ...,0.0000
4,ttfj0045,nmq76b00,85297330,,,Re: Newport Cigarette Ad Models,"Minghenelli, Sharon",Lorillard Inc.,,,...,"public, no restrictions",,,,,,,,<ocr>I would like some assurance that your Pub...,0.7003
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
94,hmlj0045,yos76b00,201069714Exhibit1781,,,"Re: R&D Cost Sharing, Confidentiality and Lice...","Kohnhorst, Earl Exec VP",Brown and Williamson Tobacco Corp.,,,...,"public, no restrictions",,,,,,,,3&o> BROIWAUUIIUISON TOBACCO CQRJOILW.QS ...,0.9493
95,pllj0045,qos76b00,301122439-301122440Exhibit11,,,Re: Cost and Risk Pooling Agreement,"*Cummins, B. D. (use Cummins, Bob D.)",Brown and Williamson Tobacco Corp.,,,...,"public, no restrictions",,,,,,,,/ A ...,0.7845
96,nnlj0045,ups76b00,LgToNON19970611.Lp,,,"Arch, et al. Plainiffs, v. The American Tobacc...","Blancato, William A Esq",Non-Tobacco Company,,,...,"public, no restrictions",,,,,,,,3&S oS/13/97 FRI 12:18 FAX 215 ...,0.5766
97,nylj0045,kqs76b00,5206627915-506628018,,,Cigarette Liability Litigation--Background and...,"James, A Fyock and Associates",R.J. Reynolds Tobacco Co.,,,...,"public, no restrictions",,,,,,,,PRIVILEGED & CONFIDENTIAL Privileged end wo...,0.5622
98,rqlj0045,urs76b00,01417830-01417840Exhibit101,,,RL Enrichment Project,,Lorillard Inc.,,,...,"public, no restrictions",,,,,,,,RL Enrichment Project INTRODUCTION This ...,0.4019

In [33]:
sql_sentiment = """
SELECT
  CASE
    WHEN mentioned = 'Non-Tobacco Company' THEN 'Non-Tobacco Company'
    ELSE 'Other'
  END AS mentioned_group,
  AVG(vader_compound_500)                    AS avg_sentiment,
  SUM(CASE WHEN vader_compound_500 IS NOT NULL THEN 1 ELSE 0 END) AS n_non_null,
  COUNT(*)                                   AS total_rows
FROM df
GROUP BY mentioned_group;
"""

In [34]:
pysqldf(sql_sentiment)

       mentioned_group  avg_sentiment  n_non_null  total_rows
0  Non-Tobacco Company       0.174162          13          13
1                Other       0.298965          86          86